### PR TITLE
enabled addTrack API for android and ios

### PR DESCRIPTION
**Pull request by yonatann**
I have enabled the new addTrack API for ios and android as well as added a few runtime checks for robustness

### CODE REVIEW

**Comment by cloudwebrtc** [comment]
LGTM

**Comment by carlfost** [comment]
Since addStream() is obsolete, and you add the addTrack(), how do you use it since pc.addTrack(audiotrack,stream) gives syntax error.

**Comment by yonatann** [comment]
The way to use it is to send a list of stream Ids not a stream object: `pc.addTrack(track, [stream.id]);`

**Comment by vladimircores** [comment]
When this API will be available in the release build? Thanx.

**Comment by animeshjain** [comment]
+1 @vladimircores 
Any idea when this will be released?

**Comment by mapkbalaji** [comment]
Please release this API. I'm unable to connect to iOS devices using addStream.

**Pull request merged**
