### PR TITLE
Implemented audio only recording in media recorder for android and ios

### PR DESCRIPTION
**Pull request by yonatann**
I added an option for audio-only recording for android and implemented audio-only recording for ios.
There is still room to implement video recording for ios.

### CODE REVIEW

**Comment by cloudwebrtc** [comment]
There seem to be three file conflicts preventing the merge

Conflicting files
```
example/android/gradle.properties
ios/Classes/FlutterWebRTCPlugin.m
ios/flutter_webrtc.podspec
```

**Comment by yonatann** [comment]
I removed the non-core files and added them to .gitignore as you requested.
If you want me to resolve the conflicts then please give me write access.

Cheers

**Comment by cloudwebrtc** [comment]
@yonatann Cool, I have added you to collaborators.

**Comment by yonatann** [comment]
@cloudwebrtc I have resolved the conflicts and pushed the modifications.
Please note that I only tested on my usage scenario which is voice only.

**Pull request merged**
