### PR TITLE
Fix onFirstFrameRendered never called on iOS #72

### PR DESCRIPTION
**Pull request by rostopira**

### CODE REVIEW

**Comment by rostopira** [comment]
@cloudwebrtc I don't know ¯\_(ツ)_/¯
Otherwise, I wouldn't request a review
Edit this PR as you wish

**Comment by cloudwebrtc** [comment]
I thought about it, it should be needed. If multiple video viewers need to be switched multiple times in the case of multiple video renderers, onFirstFrameRendered should be triggered when the new track is set.

**Comment by rostopira** [comment]
@cloudwebrtc committed, is it fine now?

**Comment by cloudwebrtc** [comment]
@rostopira 
Yes, no problem, I will merge immediately.

**Pull request merged**
