### PR TITLE
#39: Implemented MediaStreamTrack.setVolume()

### PR DESCRIPTION
**Pull request by rostopira**
Thanks @aryzhov !

### CODE REVIEW

**Comment by aryzhov** [comment]
@rostopira Dima, I appreciate the quick response. However, there's an issue with my commit. The code executes but I see no effect in the output volume - neither on iOS, nor on Android. Do you have suggestions on how to proceed?

**Comment by aryzhov** [comment]
Yes, I am using it on local streams, and that's how I thought it's supposed to work. Let me try to change it to remote stream. Also, please take a look at the change I made to FlutterRTCMediaStream.m. It populates localTracks to be later used in setVolume. I have a feeling I might not be doing things correctly there.

**Comment by rostopira** [comment]
@aryzhov Yeah, I've seen this, but that line doesn't do anything useful
If you check [media_stream.dart](https://github.com/cloudwebrtc/flutter-webrtc/blob/master/lib/media_stream.dart) you can see, that `getMediaTracks()` actually populates tracks lists, so you can later call `getAudioTracks()` to get them, so make sure you call it at least once in dart
Maybe I'm wrong about that, because obj-c code in this repo needs some refactoring

**Comment by aryzhov** [comment]
So how do I get a remote stream? `RTCPeerConnection` has `List<MediaStream> _remoteStreams` which never gets populated.

**Comment by rostopira** [comment]
@aryzhov this code should do the trick
```dart
_peerConnection.onAddStream((stream) async {
  await stream.getMediaTracks();
  stream.getAudioTracks().forEach((track) => track.setVolume(10.0));
});
```

**Comment by aryzhov** [comment]
Thanks, that works. Should I try adding code to populate _remoteStreams in order to make it convenient so change the volume during the session, not just to set it initially? Otherwise, the client has to keep its own list of audio tracks.

**Comment by rostopira** [comment]
@aryzhov I'm actually keeping list of streams, and are you sure, that `_remoteStreams` never populated? 🤔

**Comment by aryzhov** [comment]
Yes, keeping a list of streams would be better. `_remoteStreams` (as well as `_localStreams`) don't not get populated, I double-checked. They either need to be removed, or there needs to be logic added to populate them. For now, I'll add one more commit to undo the unnecessary changes in `FlutterRTCMediaStream.m`, as well as to clean up the log messages I added.

**Pull request merged**
